name: ivr-unity
region: nyc

services:
  # Backend API Service (Telnyx + ElevenLabs Bridge)
  - name: ivr-backend
    github:
      repo: terrizoaguimor/ivr-unity
      branch: main
      deploy_on_push: true
    source_dir: ivr-unity-backend
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: info
      - key: TELNYX_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: TELNYX_PUBLIC_KEY
        scope: RUN_TIME
        type: SECRET
      - key: TELNYX_CONNECTION_ID
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_AGENT_ID
        scope: RUN_TIME
        type: SECRET

  # Dashboard Frontend (Next.js with Glassmorphism UI)
  - name: ivr-dashboard
    github:
      repo: terrizoaguimor/ivr-unity
      branch: main
      deploy_on_push: true
    source_dir: ivr-unity-dashboard
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${ivr-backend.PUBLIC_URL}
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_AGENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: HTPASSWD_USER
        scope: RUN_TIME
        type: SECRET
      - key: HTPASSWD_PASS
        scope: RUN_TIME
        type: SECRET

ingress:
  rules:
    - component:
        name: ivr-dashboard
      match:
        path:
          prefix: /
    - component:
        name: ivr-backend
      match:
        path:
          prefix: /api
    - component:
        name: ivr-backend
      match:
        path:
          prefix: /telnyx
    - component:
        name: ivr-backend
      match:
        path:
          prefix: /stream
    - component:
        name: ivr-backend
      match:
        path:
          prefix: /health
