name: ivr-unity
region: nyc

services:
  # Backend API Service (Telnyx + ElevenLabs Bridge)
  - name: ivr-backend
    github:
      repo: terrizoaguimor/ivr-unity
      branch: main
      deploy_on_push: true
    source_dir: ivr-unity-backend
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    routes:
      - path: /telnyx
        preserve_path_prefix: true
      - path: /stream
        preserve_path_prefix: true
      - path: /health
        preserve_path_prefix: true
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: info
      - key: TELNYX_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: "KEY019C02198905775761880166D9BE5825_lzDW4IvyRa7WmsIKaNvgUD"
      - key: TELNYX_PUBLIC_KEY
        scope: RUN_TIME
        type: SECRET
        value: "2B78EeckMuSxSvpcq6D2sUG/UAlh/i57yZguvDTU/Mg="
      - key: TELNYX_CONNECTION_ID
        scope: RUN_TIME
        type: SECRET
        value: "mock_connection_id"
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: "sk_dd91fb09de472750ce3e99df73978cdff4f2614f7d6c1cd9"
      - key: ELEVENLABS_AGENT_ID
        scope: RUN_TIME
        type: SECRET
        value: "agent_4801kg64ffw3f4q8vdytf5j7yz85"

  # Dashboard Frontend (Next.js with Glassmorphism UI)
  - name: ivr-dashboard
    github:
      repo: terrizoaguimor/ivr-unity
      branch: main
      deploy_on_push: true
    source_dir: ivr-unity-dashboard
    build_command: npm install && npm run build && cp -r public .next/standalone/ 2>/dev/null || true && cp -r .next/static .next/standalone/.next/
    run_command: node .next/standalone/server.js
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${ivr-backend.PUBLIC_URL}
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: "sk_dd91fb09de472750ce3e99df73978cdff4f2614f7d6c1cd9"
      - key: ELEVENLABS_AGENT_ID
        scope: RUN_TIME
        type: SECRET
        value: "agent_4801kg64ffw3f4q8vdytf5j7yz85"
      - key: AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "ivr-unity-jwt-secret-2024"
      - key: ADMIN_USERNAME
        scope: RUN_TIME
        type: SECRET
        value: "unity"
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "UnityIVR2024"
