name: ivr-unity
region: nyc
services:
  - name: web
    github:
      repo: terrizoaguimor/ivr-unity
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
